### PR TITLE
Inverter api rewrite

### PR DESCRIPTION
**Pull request by guglicap**
rewrote the Inverter class API to be more user-friendly.
@PA4WD unfortunately I can't test it, would you mind trying it? I would also like to hear your thoughts on these changes. Thanks

### CODE REVIEW

**Comment by PA4WD** [comment]
i get the error
"error: uninitialized reference member 'Inverter::_conn' [-fpermissive]"
in this code
```
Inverter::Inverter(Stream& conn, uint16_t addr) {
	_conn = conn;
	_addr = addr;
}
```
My C++ knowledge is not very good, i am more a C guy.

**Comment by guglicap** [comment]
Alright, it was compiling for my Arduino UNO but I tried compiling it for nodemcu and I got the same error. 
I made sure it now compiles for both. 
I also changed the API not to expose the layout retrieving part, as I think that isn't really relevant to the end user.

**Comment by PA4WD** [comment]
I tested it quickly, begin return always false (CMD_ERR in parseFrame )
I can not test any further, this is a small project at work to generate data to experiment with node-red and grafana.
Thanks for the help.

**Comment by guglicap** [comment]
Tested and it's working. Merging.

**Pull request merged**
